- name: Demo on printing
  hosts: localhost
  tasks:
    - name: Print Hello World
      ansible.builtin.debug:
         msg: Hello World

- name: Demo on variables
  hosts: localhost
  vars:
     url: example.com
  tasks:
    - name: Print Hello World
      ansible.builtin.debug:
        msg: "{{url}}"


