- name: Demo on conditions
  hosts: localhost
  tasks:
    - name: Print apple price
      ansible.builtin.debug:
         msg: price of apple is - 1$
      when: fruit == "apple"

    - name: Print orange price
      ansible.builtin.debug:
        msg: price of orange is - 2$
      when: fruit == "orange"